version: "3.7"

services:
    doc:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ${PWD}/src:/home/node
      ports:
        - 3000:3000
      command: docsify serve .
